### ISSUE TITLE
Add a parameter to enable/disable recursive processing

### ISSUE THREAD

**Issue by jstastny-cz** [kiegroup/unpack-build-maven-plugin#2]
Add a parameter to control whether the plugin should stop at root level or continue to sub modules in recursive manner.

Proposed parameter definition:
```
    @Parameter(property = "unpackbuild.recursive", defaultValue = "false")
    private boolean recursive;
```
Which changes existing behavior due to the default value. @baldimir what do you think about the default mode? Recursion or not?

**Comment by baldimir** [comment]
I think if the parameter is called "recursive", the default should be non-recursive. However we need to make sure the change is adapted in the current usages, because it will be changing the previous behaviour.
